

POST http://127.0.0.1:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="cat_name"

Walter Phillip
--MyBoundary
Content-Disposition: form-data; name="weight"

6
--MyBoundary
Content-Disposition: form-data; name="owner"

Amber
--MyBoundary
Content-Disposition: form-data; name="birthdate"

2020-07-05
--MyBoundary
Content-Disposition: form-data; name="cat"; filename="walter.jpeg"
Content-Type: image/jpeg

< ./public/walter.jpeg

--MyBoundary--